### ISSUE TITLE
TypeError when importing Credentials

### ISSUE THREAD

**Issue by dtcorrea** [IBM/ibm-generative-ai#10]
ibm-generative-ai v 0.1.14
Python 3.9.16

When I try importing `from genai.model import Credentials` I receive the error `TypeError: issubclass() arg 1 must be a class`. It seems to be a dependency issue. One of the dependencies, pydantic, depends on typing-extensions >=4.2.0 and when I install bm-generative-ai it installs typing-extensions 4.6.0. The error goes away when I downgrade typing-extensions to 4.5.0 and everything I tried so far runs well.

**Comment by onkarbhardwaj** [comment]
@dtcorrea : Would it be possible for you to make a PR for this? Would be great to have you as a contributor. Feel free to create a fork, edit `pyproject.toml` for the dependency, and then create a PR into upstream.

Otherwise, we will be happy to fix.

**Comment by dtcorrea** [comment]
Hi @onkarbhardwaj . I was going to submit a PR but testing it again with the newest pydantic and typing-extensions releases there is no error anymore. The bug was fixed and, if relevant at all, you can see a background on the issue [here](https://github.com/pydantic/pydantic/issues/5821) and [here](https://github.com/python/typing_extensions/issues/179). I'm closing this issue. Thanks for looking into it!
