### ISSUE TITLE
Pydantic Params Objects : allow extra field

### ISSUE THREAD

**Issue by vedem1192** [IBM/ibm-generative-ai#111]
**Context**

With increasing feature in the API, it would be great to enable users to pass new (extra) parameters to the params objects (such as the GenerateParams object). This will allow the user to make use of new features related to the generate method as they are release.
Example : Passing the new `beam_width` param

**Alternatives**

Wait for the team to release a new version of the param object

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by onkarbhardwaj** [comment]
This is partially fixed in #110 (ability to pass extra parameters). Rest of this issue is similar to issue #112

**Comment by vedem1192** [comment]
in PR #110
