### ISSUE TITLE
Pydantic GenerateParams allow extras

### ISSUE THREAD

**Issue by florenzi002** [IBM/ibm-generative-ai#134]
### Version Information
 - Package Version: 0.2.3
 - Operating System: MacOS Ventura 13.3.1

```python
class GenerateParams(BaseModel):
    class Config:
        anystr_strip_whitespace = True
        extra = Extra.allow
        allow_population_by_field_name = True
```
allows for something like this 
```python
params = GenerateParams(my_param=99)
```
which leads to 
```
GenAiException: b'{"status_code":400,"error":"Bad Request","message":"\'my_param\' property is not expected to be here.","extensions":{"code":"INVALID_INPUT","state":[{"message":"\'my_param\' property is not expected to be here","suggestion":"Did you mean property \'stream\'?","instancePath":"body.parameters","params":{"errorType":"additionalProperties"}}]}}'
```

### What is the expected behavior?
Extras are not allowed if they are not supported for generation at API level

### What is the actual behavior?
They are allowd in the lib but break at the api

### Any possible solutions?
extra = Extra.ignore

### Can you identify the location in the GENAI source code where the problem exists?
https://github.com/IBM/ibm-generative-ai/blob/f7680ea11e280f39a13ca247fbb1ca3066430f52/src/genai/schemas/generate_params.py#L51

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Tomas2D** [comment]
Hello @florenzi002, this behaviour is desired because there can be some extra non-documented parameters on the API. Implicitly forbidding new parameters would prevent users from trying new features immediately.

To solve your problem, you can take this approach.
```python
GenerateParams.Config.extra = Extra.ignore
params = GenerateParams(demo=1)
```

or

```
class MyGenerateParams(GenerateParams):
    class Config(GenerateParams.Config):
        extra = Extra.ignore


params = MyGenerateParams(demo=1)
```

Let me know if this helps.

**Comment by florenzi002** [comment]
Right... that actually helps me!
I wasn't aware of undocumented params being a thing 😄
