### ISSUE TITLE
cannot import name 'version' from 'genai._version'

### ISSUE THREAD

**Issue by janpeter123** [IBM/ibm-generative-ai#137]
### Version Information
 - Package Version: 0.2.5 
 - Operating System: MacOS (Intel Slicion)

### What is the expected behavior?
When i run this code

```
from genai.model import Credentials, Model
from genai.schemas import GenerateParams

```

### What is the actual behavior?
I get the following error in Python

```
`ImportError: cannot import name 'version' from 'genai._version' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/genai/_version.py)
`
```
### Please provide a unit test that demonstrates the bug.
Don't have unit test

### Other notes on how to reproduce the issue?
Install the latest version of ibm-generative-ai, (0.2.5)

**Comment by Tomas2D** [comment]
Hello @janpeter123, I could not reproduce the issue you are having. 

Can you please create a test repository with the exact configuration causing the error? 
I will then take a look at it.
