### ISSUE TITLE
switch from freeform to prompt builder breaks the prompt

### ISSUE THREAD

**Issue by krishnac7** [IBM/ibm-generative-ai#140]
### What is the expected behavior?
Switching between Prompt Builder UI and free-form text is breaking the formatting and the placement of the instructions

### What is the actual behavior?
Switching back from freeform should not put the instruction into examples

### Other notes on how to reproduce the issue?
is reproducible with any input

### Any possible solutions?
using different standard delimiters to separate the instruction set, examples, and the testing cases

### If the bug is confirmed, would you be willing to submit a PR?
yes

Yes / No _(Help can be provided if you need assistance submitting a PR)_
yes

**Comment by Tomas2D** [comment]
This is not related in any way to the Python SDK.
