### ISSUE TITLE
LangChainInterface doesn't override get_num_tokens etc

### ISSUE THREAD

**Issue by ind1go** [IBM/ibm-generative-ai#232]
### Version Information
 - Package Version: 0.3.1
 - Operating System: MacOS Sonona

### What is the expected behavior?

Calling `get_num_tokens` or `get_num_tokens_from_messages` on a `LangChainInterface` would return the right number.

### What is the actual behavior?

It actually uses the GPT2 tokenizer (falling back to `langchain/schema/language_model.py`, function `get_tokenizer()`), and comes out with the wrong number.

### Please provide a unit test that demonstrates the bug.

```python
llm = LangChainInterface(credentials=credentials, model="meta-llama/llama-2-70b-chat", params=params)
print(llm.get_num_tokens(prompt_text))
# ...vs...
model = Model("meta-llama/llama-2-70b-chat", params=TokenParams, credentials=credentials)
tokenized_response = model.tokenize([prompt_text], return_tokens=True)
print(tokenized_response[0].token_count)
```

### Any possible solutions?

I note it's implemented on the chat interface, just not on plain `LangChainInterface` yet - so I'm registering my interest in it being fixed or fixing it there too.

I also note that `get_token_ids` isn't implemented for either so it would also be giving the GPT2-based result.

### Can you identify the location in the GENAI source code where the problem exists?

```
src/genai/extensions/langchain/llm.py
```

### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by Tomas2D** [comment]
Hey @ind1go, good catch.

I will ensure this will be delivered in the upcoming release (next week)
