### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by vedem1192** [IBM/ibm-generative-ai#24]
### Description
Go through the built documentation site and update as needed
More specifically, we want to : 
- add more relevant examples (langchain)
- update examples to add the credentials object with api_endpoint
- fix typos in PromptPattern Quick start
- add documentation on the local server feature (the extension expects a user to define their model as shown in the example, ask james for more specific info)

**Comment by vedem1192** [comment]
Sphinx Documentation:
- example section : group examples by functionality (add a new level/subsection)
  - templates will need to go under assets
```
Examples
  - Simple Examples (Getting Started)
        - Generate
        - Tokenize
        ...
  - Async Examples 
  - Local Server (locally served models)
  - Prompts 
  - Extensions
     - Langchain
     - Pandas
     - HuggingFace
```
- Update example imports to import Credentials, Model, Metadata from genai (not genai.model)
```
from genail import Credentials, Model, Metadata
```

Action item : 
- @vedem1192  : Get back to Young and Mairead regarding which examples we want to add to the sphinx pages
- @moneill0  : Sync with James for localserver tutorial and add it to Sphinx doc
- @jayolee  :  looking into linking examples from the repo inside the sphinx doc (so we don't have to update in multiple places)

**Comment by onkarbhardwaj** [comment]
Update pre-requisites in the installation section of README with python and pip requirements @jayolee @moneill0

**Comment by jayolee** [comment]
Update the model param of Model class's type hinting- Instead of being just ModelType, `Union[ModelType, str]`

**Comment by vedem1192** [comment]
Add example in the "Getting Started" section that import models by string name 
Add a note in the readme.md (along with the pre-requisites) can import model with string

**Comment by jayolee** [comment]
Add extension installation explanation link to the doc
