### ISSUE TITLE
DOCS : Add documentation on how to cite the toolkit

### ISSUE THREAD

**Issue by DhavalRepo18** [IBM/ibm-generative-ai#248]
**What type of documentation needs to be updated?**
[ ] [README file](/README.md)

**Is your documentation update related to a problem/software issue? Please describe.**
The researcher would like to Ack the toolkit for enabling the experiment.  We should add a "How to cite" section in the readme section. 

**Additional context**
Add any other context or screenshots about how documentation must be updated.

**Comment by Tomas2D** [comment]
Hey, we will add the following citation section to the new SDK version.

## BibLaTeX

```latex
@online{ibm_generative_ai_sdk,
  author       = {IBM},
  title        = {IBM Generative AI Python SDK (Tech Preview)},
  year         = {2024},
  url          = {https://github.com/IBM/ibm-generative-ai},
  urldate      = {2024-01-02}
}
```

## BibTex

```latex
@misc{ibm_generative_ai_sdk,
  author       = {IBM},
  title        = {IBM Generative AI Python SDK (Tech Preview)},
  howpublished = {\url{https://github.com/IBM/ibm-generative-ai}},
  note         = {Accessed 2024-01-02},
  year         = {2024}
}
```

**Comment by Tomas2D** [comment]
Added to the documentation and README.
