### ISSUE TITLE
How to pass data parameter to LangChainInterface when using generation(`Named entity recognition`) api.

### ISSUE THREAD

**Issue by xiaobitipao** [IBM/ibm-generative-ai#285]
### Version Information
* Python 3.11
* Package Version: 2.0.0
* Operating System: MacOS

### What is the expected behavior?
I expect it can be used in conjunction with `langchain` when using generation(`Named entity recognition`) api.

### What is the actual behavior?
When I use the `generation` api to handle `Named entity recognition`, in addition to `parameters` and `moderations`, there is also a `data` parameter in the body. for example:
```json
{
    "data": {
        "input": "Microsoft has seen declining market share in the EU, Eric Schmidt said.",
        "instruction": "The following document is a transcript from a financial earnings call.  Read the document and then write a short 1 paragraph summary.",
        "input_prefix": "Input:",
        "output_prefix": "Entities:",
        "examples": [
            {
                "input": "\"IBM is a competitor of Google in the US\" said Rami Swarthmore.",
                "output": "IBM: company, Google: company, US: country, Rami Swarthmore: person"
            }
        ]
    }
}
```

While using `client.text.generation.create_stream` function I can pass `data` parameter in dict type, because the `data` parameter is of type `Optional[ModelLike[PromptTemplateData]]`.

```python
generator = client.text.generation.create(
    model_id=model_id,
    inputs=input,
    parameters=parameters,
    moderations=moderations,
    data={data above}
)
```

If I use langchain, how should the `data` parameter be passed? I tried passing the `data` parameter to `LangChainInterface`, but an exception occurred: instance of PromptTemplateData expected. because the `data` parameter is of type `Optional[PromptTemplateData]`.

```python
llm = LangChainInterface(
    model_id=model_id,
    client=client,
    parameters=parameters,
    moderations=moderations,
    data={data above}
)
response = llm.stream(input)
```

How should I use the `data` parameter in LangChainInterface?

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Tomas2D** [comment]
Hey @xiaobitipao,

The following code will work as soon as we deploy a fix which prevents removing the `model_id` parameter when the `prompt_id` is present. This fix will be deployed on Monday/Tuesday.

```python
client = Client(credentials=Credentials.from_env())
llm = LangChainInterface(
    client=client,
    model_id="ibm/granite-13b-instruct-v2",
    prompt_id="prompt_builder",
    parameters=TextGenerationParameters(return_options=TextGenerationReturnOptions(input_text=False, input_tokens=True)),
    data=PromptTemplateData.model_validate({
        "input": "Microsoft has seen declining market share in the EU, Eric Schmidt said.",
        "instruction": "The following document is a transcript from a financial earnings call.  Read the document and then write a short 1 paragraph summary.",
        "input_prefix": "Input:",
        "output_prefix": "Entities:",
        "examples": [
            {
                "input": "\"IBM is a competitor of Google in the US\" said Rami Swarthmore.",
                "output": "IBM: company, Google: company, US: country, Rami Swarthmore: person"
            }
        ]
    })
)
for chunk in llm.invoke(""):
    print(chunk)
```

**Comment by xiaobitipao** [comment]
@Tomas2D 
Great!
I will confirm after the new version is released.

**Comment by Tomas2D** [comment]
@xiaobitipao released in v2.1.0. Can you verify?

**Comment by xiaobitipao** [comment]
@Tomas2D 
I've confirmed that it works fine when using the `llm.invoke("")` function.

There is one more thing I would like to ask.
When I want to return a `Streaming response` through LangChain, which of the following methods should I choose?
1. Use the `llm.stream()` function and process the response
2. When creating a `LangChainInterface` instance, pass the `streaming` parameter and use `llm.invoke("")` function

I think the first one should be used.
My question is that the `llm.stream()` function requires an `input` parameter, but the `input` parameter has been passed in the `data` parameter of the `LangChainInterface` instance, so I think this `input` parameter should not be a required parameter.

**Comment by xiaobitipao** [comment]
@Tomas2D 
Or like `llm.invoke("")`, I just use `llm.stream(input='')`.

**Comment by xiaobitipao** [comment]
@Tomas2D 
I confirmed that `llm.stream(input='')` executes correctly. The issue can be closed.
Thank you.
