### ISSUE TITLE
DOCS: watsonx.ai enpoints instead of bam-api.res.ibm.com

### ISSUE THREAD

**Issue by Max-Jesch** [IBM/ibm-generative-ai#322]
**What type of documentation needs to be updated?**
[X] [API documentation](https://ibm.github.io/ibm-generative-ai/)
[ ] [Code of Conduct (CoC)](/CODE_OF_CONDUCT.md)
[ ] [Contribution Guide](/DEVELOPMENT.md)
[ ] [README file](/README.md)
[ ] [Project Team](/ACTIVE_PROJECT_TEAM.md)

I cannot find documentation about how to use watsonx.ai instead of bam-api.res.ibm.com . I think there should be information about this, or am I missing something?

In my opinion references to the IBM internal platform like [here ](https://ibm.github.io/ibm-generative-ai/v2.1.1/rst_source/genai.credentials.html#module-genai.credentials) should be avoided, since this is a public asset.

**Comment by Tomas2D** [comment]
We have links to the WatsonX SDK/Documentation on the homepage of this repository.
