### ISSUE TITLE
Error message when trying to use watsonx.ai

### ISSUE THREAD

**Issue by Max-Jesch** [IBM/ibm-generative-ai#324]
**Context**

I spent a few hours trying to get this SDK to work with watsonx.ai. With the help of @Tomas2D I found out that this is not supported. It would have been super helpful to get a proper error message that tells me that based on the "GENAI_API" that I provided

**Alternatives**

It would also be useful to be very clear about this in the documentation. The current documentation led me to believe this should be compatible with watsonx.ai

**Comment by Tomas2D** [comment]
The information that the SDK is incompatible with `watsonx.ai` is mentioned at the very beginning of our README.

>This is not the [watsonx.ai](https://www.ibm.com/products/watsonx-ai) Python SDK. This is the Python SDK for the Tech Preview program for IBM Foundation Models Studio. This SDK brings IBM Generative AI (GenAI) into Python programs and provides useful operations and types.
