### ISSUE TITLE
genai.schemas is missing

### ISSUE THREAD

**Issue by gyliu513** [IBM/ibm-generative-ai#340]
```
    from genai.schemas import GenerateParams as GenaiGenerateParams
ModuleNotFoundError: No module named 'genai.schemas'
```

How to install this package? Seems `pip install ibm-generative-ai` does not contain `genai.schemas`.

**Comment by Tomas2D** [comment]
`genai.schemas` does not exists in SDK v2, see [Migration Guide](https://ibm.github.io/ibm-generative-ai/v2.2.0/v2_migration_guide.html).
