### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by csbobby** [IBM/ibm-generative-ai#341]
### Version Information
 - Package Version: 2.2.0
 - Operating System: Linux

### What is the expected behavior?
Run a program to call APIs under the global http proxy setting
### What is the actual behavior?
<img width="559" alt="image" src="https://github.com/IBM/ibm-generative-ai/assets/13518324/68279a58-fde7-4896-8f76-b2755f38de9d">

**Comment by Tomas2D** [comment]
The default SDK's endpoint is `https://bam-api.res.ibm.com`, which does not require any special network configuration.

**Comment by csbobby** [comment]
Thank you for the response. 
Our cluster supports the SDK endpoint, but cluster nodes need to use a proxy, this works for most of pkgs. And this pkg doesn't seem to provide a method for us to do so.
@Tomas2D

**Comment by Tomas2D** [comment]
You can do it by setting `GENAI_API` variable or by passing the value to the `Client` class directly.
