### ISSUE TITLE
configurable retries for generate_async

### ISSUE THREAD

**Issue by VaisakhiMishra** [IBM/ibm-generative-ai#38]
**Context**

re: https://github.com/IBM/ibm-generative-ai/issues/15 which deals with enabling retries using exponential backoff, it would be useful if the number of retries were also configurable at client-side with a hardcoded maximum at server side.  this request is for for `generate_async` (and its corresponding synchronous version , if it exists) functions. 

an example: 
current call of `generate_async` today: 

```
for result in model.generate_async(prompts, ordered=True, callback=xxx):
        if result is not None:
             xxx
        else:
            xxx
``` 

proposed change: 
```
for result in model.generate_async(prompts, ordered=True, callback=xxx, retries=10):
        if result is not None:
             xxx
        else:
            xxx
``` 

**Alternatives**

unaware

**Has the feature been requested before?**

probably not

**If the feature request is approved, would you be willing to submit a PR?**

no

**Comment by onkarbhardwaj** [comment]
Hi @VaisakhiMishra , currently there are no plans to implement this feature. We have a retry-related PR #36 pending that handles some of the instability on deployment (e.g., retries a few times after getting service unavailable error) and we already have safeguards in place to retry the initial connection establishment three times. We don't want to make this further configurable, as not only this can make the interface complicated but also it can cause users to keep naively retrying requests a lot of times despite system being unavailable.

If the connection can't be established within three retries, and after connection establishment the request cannot be fulfilled in a reasonable number of attempts (see #36), then it is either a deployment issue or an issue with user setup (requests being wrong or network being down more than momentarily). And at that point we are going to stop retrying.

**Comment by onkarbhardwaj** [comment]
Closing this issue for now. Could be re-opened in future if a need arises.
