### ISSUE TITLE
generate non-none result for failed prompts on generate_async

### ISSUE THREAD

**Issue by VaisakhiMishra** [IBM/ibm-generative-ai#39]
**Context**

currently, [generate_async](https://github.com/IBM/ibm-generative-ai/blob/23f2a42a706b7fb8d99c21da0ddac909528ca1ba/src/genai/model.py#L123-L168) returns a result with `input_text` and `generated_text` as its keys, but returns `None` if model fails in processing the prompt (because of network issues / character limit etc) . 

however, a `None` result for failed input can be replaced by a result object with `result.generated_text=None` , `result.input_text={input_prompt}`, `result.index={index_of_failed_prompt_in_input_list_of_str}`

this is useful if a large number of inputs is being processed asynchronously and client app needs to know which prompt failed.  

an example: 
current call of `generate_async` today (when it fails) looks like the following screenshot: 

<img width="1437" alt="image" src="https://github.com/IBM/ibm-generative-ai/assets/23708803/442f74ab-02d8-4b39-a631-0952564ad5c8">

the number `179/3740` indicated in the screenshot is not the index of the failed prompt in the input list. (comparing the string content of prompts in input list with the string content of failed prompts is tedious and needs manual work) 

proposed change: 

```
failed_prompt_list = []
for result in model.generate_async(prompts, ordered=True, callback=xxx):
        if result.generated_text is not None:
             xxx
        else:
            failed_prompt_list.append(result.index)
            # do further processing 
``` 

**Alternatives**

unaware

**Has the feature been requested before?**

probably not

**If the feature request is approved, would you be willing to submit a PR?**

no

**Comment by onkarbhardwaj** [comment]
Thanks for raising this. We have this on our roadmap.

**Comment by onkarbhardwaj** [comment]
Hi @VaisakhiMishra : For a workaround that avoids tediousness, you can use `ordered=True` and additionally keep an index variable
```python
tracker = 0
for response in model.generate_async(prompts, ordered=True):
    if response is not None:
         ...
    else:
        failed_prompts_indices.append(tracker)
    tracker += 1
```
