### ISSUE TITLE
Deprecating ModelType in favor of string naming

### ISSUE THREAD

**Issue by vedem1192** [IBM/ibm-generative-ai#42]
**Context**

ModelType is causing issue since models get deprecated or spin up regularly. Users also don't seems to understand a string can be passed as the model name. 

Would be good to add a deprecation warning for a few weeks, then deprecate the class altogether.

**Alternatives**

Keeping as is. 

**Has the feature been requested before?**

No

**Comment by assaftibm** [comment]
Hi, I'm using this package, and moving to strings sounds good.
In my case I'm using a model that isn't in the enums so my first thought was that it won't be supported.

**Comment by onkarbhardwaj** [comment]
This should be done in two phases:
1. Change all the examples and all sources documentation. Additionally, add deprecation warning, and notify userbase wherever we can reach them about this change.
2. A few weeks down the line, remove the class.
