### ISSUE TITLE
PyPi Description missing

### ISSUE THREAD

**Issue by vedem1192** [IBM/ibm-generative-ai#43]
### Version Information
 - Package Version: 0.1.15

### What is the expected behavior?

There should be a package description on the PyPi page.

### What is the actual behavior?

On new release, the description of the package gets removed.

### Please provide a unit test that demonstrates the bug.

<img width="1327" alt="Screenshot 2023-06-19 at 10 20 13 AM" src="https://github.com/IBM/ibm-generative-ai/assets/22043067/b66b8f33-c2bd-4b6e-a5c2-4d59a5790ce4">
<img width="1327" alt="Screenshot 2023-06-19 at 10 20 06 AM" src="https://github.com/IBM/ibm-generative-ai/assets/22043067/6aceeb3f-42ee-4459-948e-524515f0b3fb">

Yes / No _(Help can be provided if you need assistance submitting a PR)_
Yes

**Comment by jpwsutton** [comment]
I think I've got the fix for this in PR https://github.com/IBM/ibm-generative-ai/pull/49. I just need to validate it with the test pypi using the github actions in my own repo fist.

**Comment by onkarbhardwaj** [comment]
Closed with #49
