### ISSUE TITLE
Can't use IBM Gen AI

### ISSUE THREAD

**Issue by janpeter123** [IBM/ibm-generative-ai#75]
### Version Information
 - Package Version: 0.1.19
 - Operating System: MacOs Ventura 13.4.1

### What is the expected behavior?
When I run the sample script on the page below

`[Internal URL]/docs/ibm-generative-ai#getting-started`

The generative AI library should return me the sample output

```
Very well thanks, how are you?
Clement, but chilly.
```

### What is the actual behavior?

Instead I'm getting the following error

`{"status_code":401,"error":"Unauthorized"}`

I have already tried to regenerate my API Key but I'm still facing the same error.
It solved only when I changed the API Endpoint

### Any possible solutions?

The URL showing on the documentation is wrong

### Can you identify the location in the GENAI source code where the problem exists?
It's on the readme and on the [internal docs].

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_
Yes

**Comment by jayolee** [comment]
Hi Jan, this is not an error of the package. We support different API endpoints.
The one you are using, where you got your API key, is internal only. So you need to set the API endpoint to the right one when you create `Credentials` object.
Please keep in mind that this library is not internal only. There are things that we cannot mention here.

Also, I understand your confusion. We'll update the internal documentation to only talk about internal things to avoid confusion. I'll send you an additional documentation you can refer to.
Thanks for reporting!
