### ISSUE TITLE
 Add new parameter to sampling method.

### ISSUE THREAD

**Issue by mirianfsilva** [IBM/ibm-generative-ai#80]
**Context**

Add `typical_p` sampling parameter to generate params. This parameter only applies in sampling mode. It's value must be > 0 and < 1, though 1 can be used as a neutral value equivalent to disabled. But it can't be 0. 
(Also update the documentation.) 

**Alternatives**

No.

**Has the feature been requested before?**

No.

**If the feature request is approved, would you be willing to submit a PR?**

Yes.

**Comment by onkarbhardwaj** [comment]
Maybe we could also add `beam_width`.
