### ISSUE TITLE
Langchain Extension does not support Async Generation

### ISSUE THREAD

**Issue by joeswashington** [IBM/ibm-generative-ai#81]
**Context**

I am trying to run the langchain extension with IBM models asynchronously. They show how that can be done for [OpenAI for instance
](https://python.langchain.com/docs/modules/model_io/models/llms/how_to/async_llm) so I am suggesting that we make  this possible for IBM models. 

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by onkarbhardwaj** [comment]
Thanks @joeswashington for volunteering to submit a PR, assigning this issue to you. Our guidelines are here: [link](https://github.com/IBM/ibm-generative-ai/blob/main/DEVELOPMENT.md)

Preferably this should be a part of `LangChainInterface`.

**Comment by Tomas2D** [comment]
Ping @joeswashington, are you still willing to create a PR? Let us know.

**Comment by Tomas2D** [comment]
Based on my findings, async/await is supported without further changes. However, the stream support will be added soon.
