### ISSUE TITLE
Support Prompt_Id

### ISSUE THREAD

**Issue by hamedizadpanah-ibm** [IBM/ibm-generative-ai#85]
**Context**

What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

The latest APIs allow the generate method to be involved by passing a "prompt_id" field to allow the use of prompt templates
API Documents: /docs/api-reference#generate_prompt

Can you please add this to generate and langchain methods?

**Alternatives**

Can you achieve the same result doing it in an alternative way? Is the alternative considerable?
Not at the moment, all few shots learnings from watsonx platform cannot be used without "prompt_id"

**Has the feature been requested before?**

Please provide a link to the issue.

**If the feature request is approved, would you be willing to submit a PR?**

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Tomas2D** [comment]
Hello @hamedizadpanah-ibm,

You can use the `options` parameter where you add the `prompt_id` property.

Let me know if it helps.
